---
galaxy_info:
  role_name: graphics
  author: Philipp Müller
  description: Installs raster and vector graphics editors (Inkscape, GIMP, Pinta)
  license: Apache-2.0
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - workstation
    - graphics

dependencies: []
