---
# renovate: datasource=pypi depName=beets
multimedia_beets_version: "2.13.1"

# renovate: datasource=pypi depName=pyacoustid
multimedia_beets_pyacoustid_version: "1.3.1"

# renovate: datasource=github-releases depName=hrkfdn/ncspot extractVersion=^v(?<version>.*)$
multimedia_ncspot_version: "1.4.0"
